# ----
# Site

title: Physcult.Pullnfit
description: Сервис, который помогает учителям физкультуры монетизировать свою внеурочную работу.
url: https://physcult.pullnfit.ru
disqus_shortname: physcult
baseurl:

google_site_verification: 
permalink: pretty
timezone: YEKT
collections:
  case_studies:
    output: false
    permalink: /case-studies/:name/
defaults:
  - scope:
      path: ""
    values:
      header_class: "short"
  - scope:
      path: ""
      type: posts
    values:
      layout: post

# ----------
# SEO plugin

lang: en_NZ
logo: /siteicon.png
twitter:
  username: Physcult.Pulnfit
facebook:
  publisher: https://www.facebook.com/Physcult.Pulnfit
social:
  name: Physcult.Pulnfit
  links:
    - https://twitter.com/Physcult.Pulnfit
    - https://www.facebook.com/Physcult.Pulnfit
    - https://plus.google.com/+Physcult.Pulnfit
    - https://www.youtube.com/c/Physcult.Pulnfit
    - https://github.com/Physcult.Pulnfit

exclude:
  - Gemfile
  - Gemfile.lock
  - package.json

gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate
  - jekyll-archives
